development:
  app_id: '229124083771048'
  secret: 'b4cdf6e0c551aaa83957476dcd86d52d'
  callback_host: 'localhost:3000'

# production:
#   app_id: '185866364769116'
#   secret: 'd6bd05450e8254f8c0310f67d9fd3a1d'
#   canvas: 'sutalktest'
#   callback_host: 'sutalkfbgem.heroku.com'
  
production:
  app_id: '229124083771048'
  secret: 'b4cdf6e0c551aaa83957476dcd86d52d'
  canvas: 'sutalks'
  callback_host: 'sutalkfbgem.heroku.com'
